#ifndef SWOOSHFILES_H_INCLUDED
#define SWOOSHFILES_H_INCLUDED

#include "../ext_lib/Swoosh/Swoosh/ActivityController.h"
#include "../ext_lib/Swoosh/Swoosh/Game.h"
#include "../ext_lib/Swoosh/Segues/BlackWashFade.h"
#include "../ext_lib/Swoosh/Segues/CrossZoom.h"
#include "../ext_lib/Swoosh/Segues/ZoomFadeIn.h"
#include "../ext_lib/Swoosh/Segues/ZoomFadeInBounce.h"
#include "../ext_lib/Swoosh/Segues/Checkerboard.h"
#include "../ext_lib/Swoosh/Segues/WhiteWashFade.h"
#include "../ext_lib/Swoosh/Segues/SlideIn.h"
#include "../ext_lib/Swoosh/Segues/BlendFadeIn.h"
#include "../ext_lib/Swoosh/Segues/PageTurn.h"
#include "../ext_lib/Swoosh/Segues/ZoomOut.h"
#include "../ext_lib/Swoosh/Segues/ZoomIn.h"
#include "../ext_lib/Swoosh/Segues/HorizontalSlice.h"
#include "../ext_lib/Swoosh/Segues/VerticalSlice.h"
#include "../ext_lib/Swoosh/Segues/HorizontalOpen.h"
#include "../ext_lib/Swoosh/Segues/VerticalOpen.h"
#include "../ext_lib/Swoosh/Segues/PixelateBlackWashFade.h"
#include "../ext_lib/Swoosh/Segues/BlurFadeIn.h"
#include "../ext_lib/Swoosh/Segues/SwipeIn.h"
#include "../ext_lib/Swoosh/Segues/DiamondTileSwipe.h"
#include "../ext_lib/Swoosh/Segues/DiamondTileCircle.h"
#include "../ext_lib/Swoosh/Segues/CircleOpen.h"
#include "../ext_lib/Swoosh/Segues/CircleClose.h"
#include "../ext_lib/Swoosh/Segues/Morph.h"
#include "../ext_lib/Swoosh/Segues/RadialCCW.h"
#include "../ext_lib/Swoosh/Segues/Cube3D.h"
#include "../ext_lib/Swoosh/Segues/RetroBlit.h"
#include "../ext_lib/Swoosh/Segues/RetroBlit.h"

#endif // SWOOSHFILES_H_INCLUDED
